[package]
name = "mdbook-collapsed"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.9"
regex = "1"
mdbook = "0.4.40"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
